### PR TITLE
Add support for pretty printing XML

### LINKED ISSUE #560: Add support for a "formatted rendering" XML sink
Rendering an a stream of XML events to a formatted string (with indentation and newlines) can be useful for printing some pieces of data or writing them into files. 

The result of rendering a stream in a formatted manner should roughly look like this : 

```xml
<a> 
  <b>
     SomeText
  </b> 
</a> 
```

instead of 

```xml
<a><b>SomeText</b></a>
```

#### Workaround : 

Right now the workaround is to use a scala-xml sink and rendering the result. Obviously this implies an additional dependency. 

#### Notes : 

* the tracking of the indentation level can probably be achieved via a  simple`scan` on the fs2 stream
* the complexity can be that the xml text elements would have to be "interpreted"

### PR DESCRIPTION
**Pull request by satabin**
- [X] Pretty rendering `Pipe`
 - [x] Pretty `Collector`
 - [x] Documentation

Closes #560

### CODE REVIEW

**Comment by satabin** [comment]
@Baccata Does it cover what you had in mind?

**Comment by Baccata** [comment]
It very much does ! Thank you :smiley:

**Comment by satabin** [comment]
It motivated me to read again literature on PP in a streaming context, and I will seriously investigate implementing something like [this](https://okmij.org/ftp/continuations/PPYield/) in `fs2-data`

**Review by ybasket — APPROVED** [review]
LGTM

**Pull request merged**
