### PR TITLE
Add small Nix shell for development

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Comment by ybasket** [comment]
Looks like a cool addition! Could you add a small usage note to the Readme though for discoverability and for people with little Nix experience like me?

**Review by ybasket — APPROVED** [review]

**Comment by satabin** [comment]
Maybe we could go further and take the [Typelevel nix flake](https://github.com/typelevel/typelevel-nix). WDYT?

**Comment by vreuter** [comment]
> Maybe we could go further and take the [Typelevel nix flake](https://github.com/typelevel/typelevel-nix). WDYT?

@satabin I took the typelevel-nix snippet and just removed the sbt microsites section and switched the JDK to from 8 to 11. WDYT? Should there be other modifications of the typelevel base?

**Review by ybasket — APPROVED** [review]
Just tested on macOS with fresh Nix install and it worked fine 👍 

PS: Please avoid force pushes once a PR is open, makes review harder.

**Comment by vreuter** [comment]
> PS: Please avoid force pushes once a PR is open, makes review harder.

Sorry @ybasket , duly noted 😬

**Review by satabin — APPROVED** [review]
LGTM. Thanks for the contribution.

**Pull request merged**
